import pygame

PLAYER_POSITION_H = 200
PLAYER_POSITION_V = 200

FPS = 60

GRAVITY = 0.75

SCREEN_WIDTH = 800
SCREEN_HEIGHT = int(SCREEN_WIDTH * 0.8)

screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))